# -*- ruby -*-

# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.

source "https://rubygems.org/"

gem "nokogiri", "1.5.6"
gem "savon", "~>2.0"
gem "httpi", ">0"
gem "httpclient", ">0"

gem "rb-fsevent", "~>0.9.1", :group => [:development, :test]
gem "hoe-git", ">0", :group => [:development, :test]
gem "rake", "<0.9", :group => [:development, :test]
gem "rspec", ">0", :group => [:development, :test]
gem "bundler", ">0", :group => [:development, :test]
gem "hoe", ">0", :group => [:development, :test]
gem "guard", ">0", :group => [:development, :test]
gem "rcov", ">0", :group => [:development, :test]
gem "rdoc", "~>3.10", :group => [:development, :test]
gem "guard-rspec", ">0", :group => [:development, :test]
gem "hoe-bundler", ">0", :group => [:development, :test]

# vim: syntax=ruby
