# -*- ruby -*-

# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.

source "https://rubygems.org/"

gem "savon", "~>2.0"
gem "httpi", ">0"
gem "httpclient", ">0"
gem "nokogiri", ">0"

gem "rdoc", "~>4.0", :group => [:development, :test]
gem "rake", ">0", :group => [:development, :test]
gem "bundler", ">0", :group => [:development, :test]
gem "hoe", ">0", :group => [:development, :test]
gem "hoe-bundler", ">0", :group => [:development, :test]
gem "hoe-git", ">0", :group => [:development, :test]
gem "simplecov", ">0", :group => [:development, :test]
gem "rspec", "<2.99", :group => [:development, :test]
gem "guard", ">0", :group => [:development, :test]
gem "guard-rspec", ">0", :group => [:development, :test]
gem "rb-fsevent", ">0", :group => [:development, :test]

# vim: syntax=ruby
