# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "geti"
  s.version = "1.8.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jamie Macey"]
  s.date = "2013-03-19"
  s.description = "API wrapper for GETI, an ACH provider"
  s.email = "jamie@tracefunc.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "Guardfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "certify.rb",
    "config/test_credentials.yml.example",
    "doc/.DS_Store",
    "doc/implementation_notes.md",
    "doc/readme.txt",
    "geti.gemspec",
    "lib/geti.rb",
    "lib/geti/app_client.rb",
    "lib/geti/auth_client.rb",
    "lib/geti/client.rb",
    "lib/geti/response.rb",
    "lib/geti/terminal_settings.rb",
    "spec/geti_app_client_spec.rb",
    "spec/geti_auth_client_spec.rb",
    "spec/helper.rb",
    "spec/remote/geti_app_client_spec.rb",
    "spec/remote/geti_auth_client_spec.rb",
    "spec/remote/sample.pdf"
  ]
  s.homepage = "http://github.com/jamie/geti"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "API wrapper for GETI, an ACH provider"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<savon>, ["~> 1.0"])
      s.add_runtime_dependency(%q<httpi>, [">= 0"])
      s.add_runtime_dependency(%q<httpclient>, [">= 0"])
      s.add_development_dependency(%q<rake>, ["< 0.9"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<savon>, ["~> 1.0"])
      s.add_dependency(%q<httpi>, [">= 0"])
      s.add_dependency(%q<httpclient>, [">= 0"])
      s.add_dependency(%q<rake>, ["< 0.9"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<savon>, ["~> 1.0"])
    s.add_dependency(%q<httpi>, [">= 0"])
    s.add_dependency(%q<httpclient>, [">= 0"])
    s.add_dependency(%q<rake>, ["< 0.9"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

